name: Issue Automatic Actions

on:
  issues:
    types: [opened]

jobs:
  issue-moderator:
    runs-on: ubuntu-latest

    permissions:
      issues: write
      contents: read

    steps:
      - name: Check Out Repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: .github/moderation
        run: npm install

      - name: Generate Summary
        run: node .github/moderation/issue_summary.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check Banned Terms
        run: node .github/moderation/banned_terms.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}